apiName: "Haitam el Attar API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../AngularClient/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081